build:py2:
  image: jenningspc/atoml:latest
  script:
    - alias python=python2
    - python -V
    - pip2 install pytest-cov
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suite.py

build:py3:
  image: jenningspc/atoml:latest
  script:
    - alias python=python3
    - python -V
    - pip3 install pytest-cov
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suite.py
