python_2_7_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy python-scipy
    - git clone https://gitlab.com/ase/ase.git
    - pwd
    - echo $HOME
    - echo $PWD
    - echo $PYTHONPATH
    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
    - export PATH=$PWD/ase/tools:$PATH
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - cd test/
    - python --version
    - python data_setup-test.py
    - python predict-test.py
    - python fingerprint-test.py
    - python basin-test.py
    - python start_ga.py
    - python ga-test.py

python_3_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python3-numpy python3-scipy
    - git clone https://gitlab.com/ase/ase.git
    - pwd
    - echo $HOME
    - echo $PWD
    - echo $PYTHONPATH
    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
    - export PATH=$PWD/ase/tools:$PATH
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - cd test/
    - python3 --version
    - python3 data_setup-test.py
    - python3 predict-test.py
    - python3 fingerprint-test.py
    - python3 basin-test.py
    - python3 start_ga.py
    - python3 ga-test.py
