#python_2_7_tests:
#  script:
#    - apt-get update -qy
#    - apt-get install -qy python-pip python-numpy python-scipy
#    - pip install --upgrade scikit-learn
#    - git clone https://gitlab.com/ase/ase.git
#    - pwd
#    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
#    - export PATH=$PWD/ase/tools:$PATH
#    - export PYTHONPATH=$PWD/:$PYTHONPATH
#    - cd test/
#    - python --version
#    - python data_setup-test.py
#    - python feature_optimization-test.py
#    - python predict-test.py
#    - rm *.sqlite

#python_3_tests:
#  script:
#    - apt-get update -qy
#    - apt-get install -qy python3-pip python3-numpy python3-scipy
#    - pip3 install --upgrade scikit-learn
#    - git clone https://gitlab.com/ase/ase.git
#    - pwd
#    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
#    - export PATH=$PWD/ase/tools:$PATH
#    - export PYTHONPATH=$PWD/:$PYTHONPATH
#    - cd test/
#    - python3 --version
#    - python3 data_setup-test.py
#    - python3 feature_optimization-test.py
#    - python3 predict-test.py
#    - rm *.sqlite
