build:py2:
  image: continuumio/anaconda
  script:
    - python -V
    - pip install ase pytest-cov
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suit.py

build:py3:
  image: continuumio/anaconda3
  script:
    - python -V
    - pip install ase pytest-cov
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suit.py
