python_2_7_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python-pip python-numpy python-scipy
    - pip install --upgrade scikit-learn
    - pip install --upgrade coverage
    - git clone https://gitlab.com/ase/ase.git
    - pwd
    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
    - export PATH=$PWD/ase/tools:$PATH
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - cd test/
    - python --version
    - coverage run test_suit.py

python_3_tests:
  script:
    - apt-get update -qy
    - apt-get install -qy python3-pip python3-numpy python3-scipy
    - pip3 install --upgrade scikit-learn
    - pip3 install --upgrade coverage
    - git clone https://gitlab.com/ase/ase.git
    - pwd
    - export PYTHONPATH=$PWD/ase:$PYTHONPATH
    - export PATH=$PWD/ase/tools:$PATH
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - cd test/
    - python3 --version
    - coverage run test_suit.py
