build:py2:
  image: continuumio/anaconda
  script:
    - python -V
    - pip install ase pytest-cov tqdm
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suite.py

build:py3:
  image: continuumio/anaconda3
  script:
    - python -V
    - pip install ase pytest-cov tqdm
    - export PYTHONPATH=$PWD/:$PYTHONPATH
    - py.test --cov=atoml test/test_suite.py
